services:
  dbserver:
    image: mysql:8.3.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql
  api:
    build: .
    ports:
      - "3001:3001"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - API_KEY=${API_KEY}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    depends_on:
      - dbserver
volumes:
  mysqldata:
